import java.util.Scanner;
import java.text.DecimalFormat;

/**
 * Computing a value generated by a specified expression.
 *
 * Project 03
 * Stephen Sallas COMP 1210-005
 * 9/13/19
 */
public class EvalExpression
{
   /**
    * Using Math class methods to calculate a solution.
    * @param args Command line arguments - not used.
    */
   public static void main(String[] args)
   {
      //Scanner
      Scanner userInput = new Scanner(System.in);
   
      // Variables
      double x;
      double result;
      String resultString = " ";
      String ctlString = " ";
      String ctrString = " ";
      int charToLeft, charToRight;
          
      // Inputting "x"
      System.out.print("Enter a value for x: ");
      x = userInput.nextDouble();
   
      // Calculation
      result = (12.4 * Math.pow(x, 6) - 1.2 * Math.pow(x, 3));
      result += Math.sqrt(2.6 * Math.pow(x, 5) - 6.8 * x + 7);
      result /= Math.pow(x, 4) + 9; 
      System.out.println("Result: " + result);
      
      // Finding Number of Characters
      resultString = Double.toString(result);
      
      ctlString = resultString.substring(0, resultString.indexOf("."));
      ctrString = resultString.substring(resultString.indexOf(".") + 1);
      
      charToLeft = ctlString.length();
      charToRight = ctrString.length();
      
      // Printing # of Characters
      System.out.println("# of characters to left of decimal point: " 
            + charToLeft);
      System.out.println("# of characters to right of decimal point: " 
            + charToRight);
      
      // Finding and Printing Formatted Result
      DecimalFormat df = new DecimalFormat("#,##0.0###");
      System.out.println("Formatted Result: " + df.format(result));
   }
}
